### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by o15a3d4l11s2** [s4cha/Chords#1]
If you try to show `A#madd9` (I tested it in the ChordsApp) then the app crashes.
The problem is in `func keyboardNoteType(forKeyboardNoteType noteType: KeyboardNoteType, interval: Interval) -> KeyboardNoteType`, where `newIndex` is 24 and then becomes 12, which is out of bounds.

I though this could be fixed by doing `% 12` instead of `-= 12`, but it causes a problem - the C note (9) should be on the next octave (see attached image) 
<img src="https://user-images.githubusercontent.com/934385/194172063-44c762cf-a7f4-4ba4-aab4-5e17d4c9d215.png" width="250" />

I bought the ChordsApp few days ago and found this bug while using it. Then while searching for a feedback email I accidentally found the project on GitHub. I am still wrapping my head around the project. It looks quite interesting.

**Comment by s4cha** [comment]
Hi @o15a3d4l11s2, thanks for flagging this issue! It looks like it tries to display the C on a higher octave, which doesn't exist.
Maybe we should display a third octave in this case, what do you think ?

PS: I'm glad you found the code, as you might have guessed, The [Chords app](https://github.com/s4cha/ChordsApp) is powered by this framework :)

**Comment by s4cha** [comment]
Your fix works well on the core side, I think now it's in the ChordsApp code, where we'd need to display a higher octave

**Comment by s4cha** [comment]
in `Keyboard.swift` we can add a third Keyboard porting like so 
```swift
KeyboardPortion(cNote: 60, chord: chord)
KeyboardPortion(cNote: 72, chord: chord)
KeyboardPortion(cNote: 84, chord: chord)
```
and in `AppViewModel.swift` make sure we bump `kFirstCIndex` to display on the next Keyboard portion. Will push the changes soon :)

PS: B9 was crashing as well, which isn't so benign...

**Comment by o15a3d4l11s2** [comment]
I also added a third octave in the app, but the C note was still displaying on the wrong octave. I think what I was missing is `kFirstCIndex`. Looking forward to the fix. I can test it once you merge it.

**Comment by s4cha** [comment]
Latest commit on master should fix it, let me know how this goes and I'll release an update on the Appstore :)

**Comment by o15a3d4l11s2** [comment]
Works as expected, great!

I am sure you have intentionally disabled horizontal mode for iPhones, what is the reason?
I will try to check the logic to scroll/center the chord.

**Comment by s4cha** [comment]
Great, just pushed the update to the App Store.
I explicitly disabled landscape mode yes, though it would be better to view the chords, the keyboard was masking most of the screen. One of the next features I was thinking about was replacing the iPhone keyboard with a custom keyboard that would just display notes, I think that would save a lot of screen real estate. What do you think ?

Scrolling to center the chord is a great addition, I will accept pull requests of course if you want to take a shot at it 👍
